/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface ErrorResponse {
  error: string;
}

export interface SuccessResponse {
  success: boolean;
}

export interface RoadmapDay {
  day: number;
  title: string;
  tasks: string[];
  resources: string[];
}

export interface RoadmapWeek {
  week: number;
  title: string;
  days: RoadmapDay[];
}

export interface Roadmap {
  id: number;
  userId: string;
  skillName: string;
  duration: number;
  experienceLevel: string;
  overview: string;
  roadmapData: RoadmapWeek[];
  totalDays: number;
  checkedTasks: string[];
  shareToken: string;
  /** @nullable */
  rating?: number | null;
  createdAt: string;
}

export type RoadmapGenerateInputExperienceLevel = typeof RoadmapGenerateInputExperienceLevel[keyof typeof RoadmapGenerateInputExperienceLevel];


export const RoadmapGenerateInputExperienceLevel = {
  beginner: 'beginner',
  intermediate: 'intermediate',
  advanced: 'advanced',
} as const;

export interface RoadmapGenerateInput {
  /** @minLength 1 */
  skillName: string;
  /**
     * @minimum 1
     * @maximum 52
     */
  duration: number;
  experienceLevel: RoadmapGenerateInputExperienceLevel;
  save?: boolean;
}

export interface RoadmapProgressInput {
  checkedTasks: string[];
}

export interface RoadmapRatingInput {
  /**
     * @minimum 1
     * @maximum 5
     */
  rating: number;
}

export interface RoadmapStats {
  totalRoadmaps: number;
  completedRoadmaps: number;
  inProgressRoadmaps: number;
  totalTasksCompleted: number;
  skillsCovered: string[];
  averageCompletion: number;
}

export interface TrendingSkill {
  skillName: string;
  count: number;
}

